### ISSUE TITLE
Forms checkbox isnt aligned properly in firefox

### ISSUE THREAD

**Issue by sazego** [apption-oscode/elemental-blazor#139]
Hello

I just noticed that the form checkbox isnt aligned to the left in firefox. Works fine in Chrome and Edge .
Firefox:
![image](https://user-images.githubusercontent.com/107186654/172830996-bb9efd24-3da2-40ac-9b70-678a02bfe5f6.png)
Chrome/Edge:
![image](https://user-images.githubusercontent.com/107186654/172831128-b3351d81-92cf-495d-a2c0-d8cd15a61704.png)

Also as a quick heads up, the installation process in the demo page is outdated, it still shows the old name (Apption.Elemental) and the stylesheet reference is also outdated (current: href="_content/Blazor.Elemental/css/elemental.min.css", should be:     href="_content/AElemental.Blazor/css/elemental.min.css", took me a bit to find the right one).

Anyways, thank you so much for this insnaley good work. I'm using the forms with the custom validation and they are awesome!
As soon as I got time I will look through it to learn and try to build my own. I got no idea how the custom dropdowns are done and I'm keen to find out. Thanks!

**Comment by yjmrobert** [comment]
Hi @sazego thank you for the feedback and great catch on the firefox visual!

You're absolutely right that the demo page's installation is outdated, I'll spend a bit updating today (or early next week).

> I got no idea how the custom dropdowns are done and I'm keen to find out.

There's a lot of configuring you can do in the `OnConfigure` method for the form. Here's an example of registering a list of options, but there's no reason you can't pull those in dynamically.

https://github.com/ssc-sp/datahub-portal/blob/da98d08762b2ae04b2277a53adbb73530c0bdac3/WebPortal/Pages/Public/Signup.razor#L86-L90

I know @nabeelbader has done a lot with the forms components, he would be your best bet for questions but otherwise I've just set up a gitter room we can chat in!

[![Gitter](https://badges.gitter.im/aelemental/community.svg)](https://gitter.im/aelemental/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by ErikApption** [comment]
this issue can definitely be closed since we are moving to MudBlazor which resolves these issues

**Comment by ErikApption** [comment]
To clarify - we will be releasing a new package called MudBlazor.Forms which brings the same model form to mudblazor.
